- name: Remove node
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes    

  tasks:

      - name: Remove containers and all not used container stuff
        include_tasks: "playbooks/clean.yml"

      - name: Remove Git directory
        ansible.builtin.file:
          path: "{{ git_dst }}"
          state: absent

        
      
